require("dotenv").config();
module.exports = {
  USER: "user",
  ADMIN: "admin",
  FORGET_EMAIL_SUBJECT: 'Password Reset Link',
  FORGET_EMAIL_BODY: `PLEASE use this link to reset your account password`,
  EMAIL_CONFIRMATION_CODE_EXPIRY_TIME_IN_SECONDS: 180,
  FORGET_EMAIL_SUBJECT: 'Password Reset Link',
    FORGET_EMAIL_BODY: `PLEASE use this link to reset your account password`,
    EMAIL_VERIFICATION_SUBJECT: `Please Verify Your Email`,
    FORGET_PASSWORD_SUBJECT: `Reset Your Password`,
    EMAIL_CONFIRMATION_CODE_EXPIRY_TIME_IN_SECONDS: 180,
    INACTIVITY_NOTIFICATIONS_24H: 86400,
    USER_REFRESH_TOKEN_EXPIRY_IN_SECONDS: 300,
    FORGET_PASSWORD_CODE_EXPIRY_IN_SECONDS: 180,
    RESET_PASSWORD_ENDPOINT_EXPIRY_IN_SECONDS: 300,
    USER_EMAIL_OTP_ATTEMPTS: 'USER_EMAIL_OTP_ATTEMPTS',
    BLOCKED_USERS: 'BLOCKED_USERS',
    USER_REFRESH_TOKENS: 'USER_REFRESH_TOKENS',
    FORGET_PASSWORD_CODE_TRIES: 'FORGET_PASSWORD_CODE_TRIES',
    REFRESH_TOKEN_EXPIRY_DAYS: 15,
    BLOCK_USER_TEMPORARY_IN_SECONDS: 3600,
    DOMAIN: 'domain',
    CORRECT: 'correct',
    INCORRECT: 'incorrect',
    NEW: 'new',
    LEARN: 'learn',
    REVISED: 'revised',
    COMPLETED: 'completed',
    REVISED11: 'revised11',
    REVISED18: 'revised18',
    REVISED48: 'revised48',
    MASTER: 'master',
    ADMIN: 'admin',
    USER: 'user',
    UPLOAD_RESPONSE:
      'Please wait while the items are being uploaded. This might take a few minutes...',
    CATEGORY: 'category',
    TOPIC: 'topic',
    ACTIVE: 'active',
    INACIVE: 'inactive',
    MCQ: 'M.C.Q',
    QUESTION: 'question',
    LEVEL: 'level',
    LESSON: 'lesson',
    REVISED_LESSON: 'Revised Lesson',
    CRNA: 'crna',
    STUDENT: 'student',
    PROGRESS: 'progress',
    CATEGORIES: 'categories',
    TOPICS: 'topics',
    DOMAINS: 'domains',
    LEVELS: 'levels',
    LESSONS: 'lessons',
    INPROGRESS: 'in-progress',
    STATUS: 'status',
    COMPLETED_DIRECT_DEPENDENTS: 'completed_direct_dependents',
    START: 'start',
    USER_RESPONSE_TIMESTAMPS: 'USER_RESPONSE_TIMESTAMPS',
    INACTIVITY_SMS_SENT: 'INACTIVITY_SMS_SENT',
    INACTIVITY_EMAIL_SENT: 'INACTIVITY_EMAIL_SENT',
};
