require('dotenv').config();

module.exports = {
  USER: 'user',
  ADMIN: 'admin',
  FORGET_EMAIL_SUBJECT: 'Password Reset Link',
  FORGET_EMAIL_BODY: `PLEASE use this link to reset your account password`,
  EMAIL_CONFIRMATION_CODE_EXPIRY_TIME_IN_SECONDS: 180,
  EMAIL_VERIFICATION_SUBJECT: `Please Verify Your Email`,
  FORGET_PASSWORD_SUBJECT: `Reset Your Password`,
  USER_REFRESH_TOKEN_EXPIRY_IN_SECONDS: 300,
  FORGET_PASSWORD_CODE_EXPIRY_IN_SECONDS: 180,
  RESET_PASSWORD_ENDPOINT_EXPIRY_IN_SECONDS: 300,
  USER_EMAIL_OTP_ATTEMPTS: 'MED_USER_EMAIL_OTP_ATTEMPTS',
  BLOCKED_USERS: 'MED_BLOCKED_USERS',
  USER_REFRESH_TOKENS: 'MED_USER_REFRESH_TOKENS',
  USER_TOKENS: 'MED_USER_TOKENS',
  FORGET_PASSWORD_CODE_TRIES: 'MED_FORGET_PASSWORD_CODE_TRIES',
  REFRESH_TOKEN_EXPIRY_DAYS: 15,
  BLOCK_USER_TEMPORARY_IN_SECONDS: 3600,
  ACTIVE: 'active',
  INACIVE: 'inactive',
  INPROGRESS: 'in-progress',
};
